{{ if .Values.app.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace | default "web-ui" }}
  labels:
    env: {{ .Values.app.env }}
    name: {{ .Values.app.name }}
    type: {{ .Values.app.type }}
spec:
  selector:
    env: {{ .Values.app.env }}
    name: {{ .Values.app.name }}
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort}}
      {{ end }}
{{ end }}